### ISSUE TITLE
Suppress 'print' statements

### ISSUE THREAD

**Issue by mariadelmarq** [quest-bih/oddpub#6]
Hi,

Thanks for this great package! I have updated to the latest version and now I'm getting inundated with the print statements that have been added to the code:

"Screening Data and Code Availability Statements:"
"Consolidating data:"

I'm running oddpub on every paragraph of hundreds of files, so I would really like to be able to suppress these. Could they be converted to `message` instead, so that I can then use `suppressMessages` to suppress the message output? Or delete altogether from the package?

**Comment by ontogenerator** [comment]
Hi Maria,

Thank you for the suggestion, the newest version does what you requested. I have to mention, these (now) messages are meant to appear once per folder, so if you have an input of hundreds of files in the same folder, they should still only appear once. Are you calling the `open_data_search` function repeatedly on different folders?
By the way, I strongly recommend using the `future::plan(multisession)` before calling the ODDPub functions, if you have not been doing this already.
